book_shop/book_shop/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main_page_app.urls")),
    path("",include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_shop/main_page_app/urls.py
from django.urls import path 
from . import views

app_name = "main_page_app"

urlpatterns = [
    path("",views.list_books ,name="main_page"),
    path("MyCart/",views.cart ,name="cart"),
    path('signup/',views.Sign_up.as_view(),name="signup"),
]

book_shop/main_page_app/models.py
from django.db import models
from django.contrib.auth.models import User 


class Book(models.Model):
    name = models.CharField(max_length=50)
    book_description = models.CharField(max_length=500)
    image = models.ImageField()


    def __str__(self):
        return f"Name: {self.name} //// book_description: {self.book_description} //// image: {self.image}"

book_shop/main_page_app/views.py
from django.shortcuts import render, redirect
from . import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.contrib.auth import login


def add_book(request):
    if request.POST:
        name = request.POST['name']
        description = request.POST['book_description']
        image = request.FILES['image'] 

        models.Book.objects.create( name=name, book_description=description, image=image)
        
        return redirect ( reverse ('main_page_app:Book'))
    
    return render(request, "main_page_app/main_page.html")


def list_books(request):
    all_books = models.Book.objects.all()
    book_dict = {"books":all_books}
    return render(request,'main_page_app/main_page.html',context=book_dict)







def cart(request):
    return render ( request,"main_page_app/cart.html")



class Sign_up(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"




def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # 1. Kullanıcıyı oluştur ve değişkene ata
            user = form.save() 
            
            # 2. Otomatik giriş yaptır (Kritik nokta burası)
            login(request, user) 
            
            # 3. Giriş yaptıktan sonra yönlendir
            return redirect('main_page_app:cart') 
    else:
        form = UserCreationForm()
    
    return render(request, 'signup.html', {'form': form})













"""
class Sign_up(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # Manüel olarak her alana Bootstrap sınıfı ekliyoruz
        for field in form.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
        return form
"""

book_shop/main_page_app/templates/main_page_app/cart.html
{% extends "base.html" %}
{% load static %}

{%block content%}

{%endblock%}

book_shop/main_page_app/templates/main_page_app/main_page.html
{% extends "base.html" %}
{% load static %}

{%block content%}


<div style="display: flex;  gap: 10px;">
    {%for book in books %}
        <div class="card" style="width: 18rem;">
            <img src= "{{book.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{book.name}}</h5>
                <p class="card-text"> {{book.book_description}}</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    {%endfor%}
</div>


{%endblock%}

book_shop/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    
    <title>BOOKshelf</title>
</head>
<body>
    

        <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'main_page_app:main_page' %}">BOOKshelf</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Türler
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Popüler
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main_page_app:cart' %}">Sepetim</a>
                    </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <form method="post" action="{% url 'logout' %}?next=/">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary" style="padding: 7px 15px;">Log-out</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="btn btn-primary" href="{% url 'login' %}?next=/" style="padding: 7px 15px;">Log-in</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary" href="{% url 'main_page_app:signup' %}">Sign-up</a>
                            </li>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                    </li>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            </div>
        </div>
        </nav>


        {% block content %}


        {% endblock %}
</body>
</html>